steps:
  - id: test
    name: 'golang'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        go version
        go get -d -v ./...
        go test -coverprofile=coverage.out -v ./...
        go tool cover -func=coverage.out

  - id: build-docker-image
    name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t' 
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
      - '.'

images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'