version: '3'

services:
  firestore:
    image: 'mtlynch/firestore-emulator-docker:latest'
    container_name: firestore
    ports:
      - 8080:8080
    environment:
      - FIRESTORE_PROJECT_ID=dummy-project-id
      - PORT=8080

  redis:
    image: 'redis:3.2.5-alpine'
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - PORT=6379

  pubsub:
    image: 'messagebird/gcloud-pubsub-emulator:latest'
    container_name: pubsub
    ports:
      - 8681:8681
    environment:
      - PUBSUB_PROJECT1=dummy-project-id,url-clicks:url-clicks-counter
      - PORT=8681

  app:
    build: .
    container_name: url-shortener
    ports:
      - 8090:8090
    environment:
      - PORT=8090
      - GIN_MODE=debug
      - PROJECT_ID=dummy-project-id
      - FIRESTORE_PROJECT_ID=dummy-project-id
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - REDIS_HOST=redis:6379
      - REDIS_TTL=30
      - PUBSUB_TOPIC=url-clicks
      - PUBSUB_PROJECT_ID=dummy-project-id
      - PUBSUB_EMULATOR_HOST=pubsub:8681
      - ID_LENGHT=7
    depends_on:
      - firestore
      - pubsub
      - redis
